In [2]:
print("hi")

hi


2025-09-24
Numpy

In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.3'

In [7]:
L = range(1000)
%timeit L2 = [i **2 for i in L]

31.6 μs ± 3.27 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


10:00~10:20 환경 세팅 2

In [8]:
arr = np.arange(1000)
%timeit arr2 = arr **2

635 ns ± 4.38 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(arr2.ndim)

2


In [13]:
print(arr2.shape)

(3, 4)


In [18]:
arr3 = arr2.reshape(2, -1,3)

print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
print(arr3.ndim)

3


In [20]:
print(arr3.shape)

(2, 2, 3)


In [26]:
Alist = np.array([1, 2, 3, 4, 5])
Blist = np.array([6, 7, 8, 9, 10])

In [27]:
print(Alist + Blist)
print(Alist - Blist)
print(Alist * Blist)
print(Blist / Alist)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


In [33]:
print(Alist + 2)
print(Alist - 2)
print(Alist * 2)
print(Alist / 2)


[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [28]:
C_list = np.array([1, 2, 3, 4, 5])
D_list = np.array([6, 7, 8, 9])

In [29]:
print(C_list + D_list)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [30]:
E_list = np.array([1, 2, 3, 4, 5])
F_list = np.array([6, 7, 8, 9, np.nan])

In [31]:
print(E_list + F_list)

[ 7.  9. 11. 13. nan]


In [34]:
a = np.array([1 , 2 , 3])
b = np.array([10 , 20 , 30])

In [35]:
print(2 * a + b)

[12 24 36]


In [36]:
print( a == 2)

[False  True False]


In [37]:
b > 10

array([False,  True,  True])

In [38]:
(a == 2) & (b > 10)

array([False,  True, False])

In [ ]:
print(2 * a + b)
print(a == 2)
print(b > 10)
(a == 2) & (b > 10)

[12 24 36]
[False  True False]
[False  True  True]


array([False,  True, False])

In [41]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [ ]:
Z_list = [[ 0, 1, 2], [3, 4, 5]]
# 인덱싱하여 출력
# 0 ,1, 5


인덱싱

In [ ]:
Z_list[0][0]

0

In [44]:
Z_list[0][1]


1

In [45]:
Z_list[1][2]

5

In [48]:
print(Z_list[0][0])
print(Z_list[0][1])
Z_list[1][2]

0
1


5

슬라이싱


In [ ]:
Z_list = [[ 0, 1, 2], [3, 4, 5]]
# 슬라이싱 출력
# [0, 1]
# [4, 5]
# [1, 4]
print(Z_list[0])

[0, 1, 2]


In [55]:
print(Z_list[0][:2])

[0, 1]


In [56]:
print(Z_list[1][1:])

[4, 5]


In [60]:
result = [Z_list[0][1], Z_list[1][1]]

In [62]:
Y_list = np.array([[ 0, 1, 2], [3, 4, 5]])
Y_list

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
print(Y_list[0,0], Y_list[0, 1], Y_list[1, 2])

0 1 5


In [ ]:
print(Y_list[0, :2])    
print(Y_list[1, 1:])
print(Y_list[:, 1])

[0 1]
[4 5]
[1 4]


In [74]:
X_list = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11,12, 13, 14]])
X_list

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
# 슬라이싱 3회 이상 도전
print(X_list[:, 2])

print(X_list[1, :])

print(X_list[:, 1:4])

[ 2  7 12]
[5 6 7 8 9]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [88]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False,True, False,True, False,True, False,True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [89]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
arr % 2 == 0 

array([False,  True, False,  True, False,  True, False,  True])

In [95]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [97]:
arr % 2 != 0 

array([ True, False,  True, False,  True, False,  True, False])

In [99]:
arr[arr % 2 != 0]

array([1, 3, 5, 7])

In [100]:
arr2 % 2 != 0 

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [104]:
a = np.array([[1 , 2 , 3 , 4 ], [5 , 6 , 7 , 8 ], [9 , 10 , 11 , 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
a[: , [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [106]:
x = np.array ([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11 , 12 , 13 , 14 , 15 , 16 , 17 , 18 , 19 , 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
x % 3 ==0
