In [2]:
print("hi")

hi


2025-09-24
Numpy

In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.3'

In [7]:
L = range(1000)
%timeit L2 = [i **2 for i in L]

31.6 μs ± 3.27 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


10:00~10:20 환경 세팅 2

In [8]:
arr = np.arange(1000)
%timeit arr2 = arr **2

635 ns ± 4.38 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
print(arr2.ndim)

2


In [13]:
print(arr2.shape)

(3, 4)


In [18]:
arr3 = arr2.reshape(2, -1,3)

print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
print(arr3.ndim)

3


In [20]:
print(arr3.shape)

(2, 2, 3)


In [26]:
Alist = np.array([1, 2, 3, 4, 5])
Blist = np.array([6, 7, 8, 9, 10])

In [27]:
print(Alist + Blist)
print(Alist - Blist)
print(Alist * Blist)
print(Blist / Alist)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


In [33]:
print(Alist + 2)
print(Alist - 2)
print(Alist * 2)
print(Alist / 2)


[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [28]:
C_list = np.array([1, 2, 3, 4, 5])
D_list = np.array([6, 7, 8, 9])

In [29]:
print(C_list + D_list)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [30]:
E_list = np.array([1, 2, 3, 4, 5])
F_list = np.array([6, 7, 8, 9, np.nan])

In [31]:
print(E_list + F_list)

[ 7.  9. 11. 13. nan]


In [34]:
a = np.array([1 , 2 , 3])
b = np.array([10 , 20 , 30])

In [35]:
print(2 * a + b)

[12 24 36]


In [36]:
print( a == 2)

[False  True False]


In [37]:
b > 10

array([False,  True,  True])

In [38]:
(a == 2) & (b > 10)

array([False,  True, False])

In [ ]:
print(2 * a + b)
print(a == 2)
print(b > 10)
(a == 2) & (b > 10)

[12 24 36]
[False  True False]
[False  True  True]


array([False,  True, False])

In [41]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [ ]:
Z_list = [[ 0, 1, 2], [3, 4, 5]]
# 인덱싱하여 출력
# 0 ,1, 5


인덱싱

In [ ]:
Z_list[0][0]

0

In [44]:
Z_list[0][1]


1

In [45]:
Z_list[1][2]

5

In [48]:
print(Z_list[0][0])
print(Z_list[0][1])
Z_list[1][2]

0
1


5

슬라이싱


In [ ]:
Z_list = [[ 0, 1, 2], [3, 4, 5]]
# 슬라이싱 출력
# [0, 1]
# [4, 5]
# [1, 4]
print(Z_list[0])

[0, 1, 2]


In [55]:
print(Z_list[0][:2])

[0, 1]


In [56]:
print(Z_list[1][1:])

[4, 5]


In [60]:
result = [Z_list[0][1], Z_list[1][1]]

In [62]:
Y_list = np.array([[ 0, 1, 2], [3, 4, 5]])
Y_list

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
print(Y_list[0,0], Y_list[0, 1], Y_list[1, 2])

0 1 5


In [ ]:
print(Y_list[0, :2])    
print(Y_list[1, 1:])
print(Y_list[:, 1])

[0 1]
[4 5]
[1 4]


In [74]:
X_list = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11,12, 13, 14]])
X_list

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
# 슬라이싱 3회 이상 도전
print(X_list[:, 2])

print(X_list[1, :])

print(X_list[:, 1:4])

[ 2  7 12]
[5 6 7 8 9]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [88]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False,True, False,True, False,True, False,True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [89]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = [0, 2, 5]
a[idx]

array([0, 2, 5])

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
arr % 2 == 0 

array([False,  True, False,  True, False,  True, False,  True])

In [95]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [97]:
arr % 2 != 0 

array([ True, False,  True, False,  True, False,  True, False])

In [ ]:
arr[arr % 2 != 0]   

array([1, 3, 5, 7])

In [100]:
arr2 % 2 != 0 

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [104]:
a = np.array([[1 , 2 , 3 , 4 ], [5 , 6 , 7 , 8 ], [9 , 10 , 11 , 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
a[: , [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [106]:
x = np.array ([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11 , 12 , 13 , 14 , 15 , 16 , 17 , 18 , 19 , 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [108]:
x[x % 3 != 0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20])

In [109]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [107]:
x[(x % 3 == 0) & (x % 4 == 1)]


array([9])

판다스
#13:00 - 13:35 강의 자료 설명 (안 들음)

In [8]:
!pip install pandas


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import pandas as pd

In [75]:
pd.read_csv('heroes.csv')

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [76]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [77]:
pd.options.display.float_format = '{:,.0f}'.format

In [78]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [80]:
df.describe()

나이   키                 재산
count   7   7                  5
mean   34 190  2,300,278,000,120
std    13  36  5,142,800,956,894
min    18 170                600
25%    26 172         50,000,000
50%    32 177        340,000,000
75%    39 184      1,000,000,000
max    58 270 11,500,000,000,000

In [81]:
df.head(3)

이름  나이    직업     국적    키                 재산
0   아이언맨  58   CEO     미국  174 11,500,000,000,000
1     토르  45     신  아스가르드  190                NaN
2  스파이더맨  18  고등학생     미국  177                600

In [82]:
df.tail()

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [22]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [83]:
type(df['국적'])

pandas.core.series.Series

In [84]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [85]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [86]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [87]:
df['나이'].nsmallest()

2    18
5    25
3    27
6    32
4    33
Name: 나이, dtype: int64

In [88]:
df.nlargest(7,'나이')

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000
3   원더우먼  27     공주  데미스키라  178                NaN
5   캡틴마블  25    파일럿     미국  170        340,000,000
2  스파이더맨  18   고등학생     미국  177                600

In [89]:
df.nlargest(7,'키')

이름  나이     직업     국적    키                 재산
4     헐크  33  핵물리학자     미국  270      1,000,000,000
1     토르  45      신  아스가르드  190                NaN
3   원더우먼  27     공주  데미스키라  178                NaN
2  스파이더맨  18   고등학생     미국  177                600
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [90]:
df['이름']

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [91]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [32]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [33]:
df[:3]

이름  나이    직업     국적    키                 재산
0   아이언맨  58   CEO     미국  174 11,500,000,000,000
1     토르  45     신  아스가르드  190                NaN
2  스파이더맨  18  고등학생     미국  177                600

In [39]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [43]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키         재산
1     토르  45    신  아스가르드  190        NaN
3   원더우먼  27   공주  데미스키라  178        NaN
6  블랙위도우  32  스파이    러시아  170 50,000,000

In [49]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [50]:
df.loc[2:5]

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000

In [51]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [54]:
df.loc[:3, '국적':'재산']

국적    키                 재산
0     미국  174 11,500,000,000,000
1  아스가르드  190                NaN
2     미국  177                600
3  데미스키라  178                NaN

In [55]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [56]:
df[df['나이'] > 30]

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [61]:
df['나이'] < 50

0    False
1     True
2     True
3     True
4     True
5     True
6     True
Name: 나이, dtype: bool

In [64]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [65]:
df['키'] >= 180

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: 키, dtype: bool

In [66]:
df.loc[df['키'] >= 180, ['이름', '나이', '키']]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [67]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [68]:
df.drop(columns='재산')

이름  나이     직업     국적    키
0   아이언맨  58    CEO     미국  174
1     토르  45      신  아스가르드  190
2  스파이더맨  18   고등학생     미국  177
3   원더우먼  27     공주  데미스키라  178
4     헐크  33  핵물리학자     미국  270
5   캡틴마블  25    파일럿     미국  170
6  블랙위도우  32    스파이    러시아  170

In [72]:
df

이름  나이     직업     국적    키
0   아이언맨  58    CEO     미국  174
1     토르  45      신  아스가르드  190
2  스파이더맨  18   고등학생     미국  177
3   원더우먼  27     공주  데미스키라  178
4     헐크  33  핵물리학자     미국  270
5   캡틴마블  25    파일럿     미국  170
6  블랙위도우  32    스파이    러시아  170

In [92]:
df.drop(columns='재산')


이름  나이     직업     국적    키
0   아이언맨  58    CEO     미국  174
1     토르  45      신  아스가르드  190
2  스파이더맨  18   고등학생     미국  177
3   원더우먼  27     공주  데미스키라  178
4     헐크  33  핵물리학자     미국  270
5   캡틴마블  25    파일럿     미국  170
6  블랙위도우  32    스파이    러시아  170

In [93]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [99]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [100]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [97]:
df['재산'].fillna(df['재산'].mean())

0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64

In [102]:
df.fillna(method='ffill')

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18220\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190 11,500,000,000,000
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                600
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [103]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [106]:
import numpy as np
df.iloc[5, 1] = np.nan
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블 NaN    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [113]:
df.describe()

나이   키                 재산
count   6   7                  5
mean   36 190  2,300,278,000,120
std    14  36  5,142,800,956,894
min    18 170                600
25%    28 172         50,000,000
50%    32 177        340,000,000
75%    42 184      1,000,000,000
max    58 270 11,500,000,000,000

In [128]:
df['나이'].fillna(df['나이'].mean(), inplace=True)

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18220\3751468051.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['나이'].fillna(df['나이'].mean(), inplace=True)


In [109]:
# 나이 평균 구하기
df['나이'].mean

<bound method Series.mean of 0    58
1    45
2    18
3    27
4    33
5   NaN
6    32
Name: 나이, dtype: float64>

In [125]:
def add_cm(height):
    return str(height) + 'Cm'
    

df['키'].apply(add_cm)

0    174Cm
1    190Cm
2    177Cm
3    178Cm
4    270Cm
5    170Cm
6    170Cm
Name: 키, dtype: object

In [130]:
df['키'] = df['키'].apply(add_cm)
df

이름  나이     직업     국적        키                 재산
0   아이언맨  58    CEO     미국  174CmCm 11,500,000,000,000
1     토르  45      신  아스가르드  190CmCm                NaN
2  스파이더맨  18   고등학생     미국  177CmCm                600
3   원더우먼  27     공주  데미스키라  178CmCm                NaN
4     헐크  33  핵물리학자     미국  270CmCm      1,000,000,000
5   캡틴마블  36    파일럿     미국  170CmCm        340,000,000
6  블랙위도우  32    스파이    러시아  170CmCm         50,000,000

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      float64
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      object 
 5   재산      5 non-null      float64
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes
